### ISSUE TITLE
Error when importing a workflow with exotic characters

### ISSUE THREAD

**Issue by paraita** [ow2-proactive/catalog#140]
Importing a workflow with the following variable named `DOCUMENT_JSON` and its value:
```json
{      "documents": [          {              "id": "1",              "text": "This document is in English."          },          {              "id": "2",              "text": "Este documento estÃ¡ en inglÃ©s."          },          {              "id": "3",              "text": "Ce document est en anglais."          },          {              "id": "4",              "text": "æ¬æä»¶ä¸ºè±æ"          },                          {              "id": "5",              "text": "Ð­ÑÐ¾Ñ Ð´Ð¾ÐºÑÐ¼ÐµÐ½Ñ Ð½Ð°ÑÐ¾Ð´Ð¸ÑÑÑ Ð½Ð° Ð°Ð½Ð³Ð»Ð¸Ð¹ÑÐºÐ¾Ð¼ ÑÐ·ÑÐºÐµ."          }      ]  }
```

fails because of the weird characters (scroll to the far right of the value) with the following exception:

```
[2018-08-22 09:35:13,858 461159-175 WARN    o.h.e.j.s.SqlExceptionHelper] SQL Error: 1366, SQLState: 22007                                                                                              [1195/5212]
[2018-08-22 09:35:13,858 461159-175 ERROR   o.h.e.j.s.SqlExceptionHelper] (conn=575) Incorrect string value: '\xC2\x9C\xC2\xAC\xC3\xA6...' for column 'PA_VALUE' at row 1                                          
[2018-08-22 09:35:13,873 461159-175 WARN  r.e.ExceptionHandlerController] Exception: could not execute statement; SQL [n/a]; nested exception is org.hibernate.exception.DataException: could not execute statement
[2018-08-22 09:35:13,876 461159-175 WARN          o.e.j.s.ServletHandler]                                                                                                                                          
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; nested excepti
on is org.hibernate.exception.DataException: could not execute statement                                                                                                                                           
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:979)                                                                                                              
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:869)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:843)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
...
Caused by: java.sql.SQLException: Incorrect string value: '\xC2\x9C\xC2\xAC\xC3\xA6...' for column 'PA_VALUE' at row 1
Query is: insert into METADATA_KEY_VALUE (CATALOGOBJECTREVISION, PA_KEY, LABEL, PA_VALUE, ID) values (?, ?, ?, ?, ?), parameters [70,'DOCUMENTS_JSON','variable','{      "documents": [          {              "id
": "1",              "text": "This document is in English."          },          {              "id": "2",              "text": "Este documento estÃ¡ en inglÃ©s."          },          {              "id": "3",
            "text": "Ce document est en anglais."          },          {              "id": "4",              "text": "æ¬æä»¶ä¸ºè±æ"          }Ã¡        Ã©               {              "id": "5",
    "text": "Ð­ÑÐ¾Ñ Ð´Ð¾ÐºÑÐ¼ÐµÐ½Ñ Ð½Ð°Ñ                                                                           æ¬æä»¶ä¸ºè±æ
Ð¾Ð´Ð¸ÑÑÑ ÐÐ­ÑÐ¾ÑÐÐ´Ð¾ÐºÑÐ¼ÐµÐ½ÑÑÐ½Ð°ÑºÐµ."          }      ]  }',573]
Ð¾Ð´Ð¸ÑÑÑoÐ½Ð°aÐ°Ð½Ð³Ð»Ð¸Ð¹ÑÐºÐ¾Ð¼uÑÐ·ÑÐºÐµeryTool.exceptionWithQuery(LogQueryTool.java:153)
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:255)
        at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:209)
        ... 73 more
```

**Comment by ShatalovYaroslav** [comment]
It seems that this issue is happening for mariadb database. This problem doesn't appear for HSQL db that we use by default with scheduler distribution.
But still maybe we can make improvement in order not allow to push to catalog storage weird characters if it can potentially brake DB.
